package codegenerator;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class MyCodeGenerator {
    final String WORKING_DIRECTORY = System.getProperty("user.dir") + "/src/main/java/generatedSources/";

    public void createJavaFile(final String modelName, final ArrayGenerationStrategy arrayStrategy) {
        final File outputFile = new File(WORKING_DIRECTORY + modelName + "Builder.java");
        FileWriter fw = null;
        try {
            fw = new FileWriter(outputFile);
            final FormattingCodeWriter codeWriter = new FormattingCodeWriter(fw);
            codeWriter.append("// Java file generated by MyCodeGenerator");
            codeWriter.blankLine();
            codeWriter.append(
                    "package generatedSources;",
                    "public class " + modelName + "Builder {",
                        "public static " + arrayStrategy.getArrayType() + " create" + modelName + "() {",
                                arrayStrategy.getArrayType() + " " + modelName + " = {",
                                arrayStrategy.getArrayContent(),
                            "};",
                            "return " + modelName + ";",
                        "}",
                    "}"
            );
            System.out.println("Writing to " + WORKING_DIRECTORY + modelName + "Builder.java");
            codeWriter.write();
            System.out.println("Done.");
            fw.close();
        } catch(Exception ex) {
            try {
                fw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            System.err.println("Exception writing file: " + ex);
        }
    }
}

