import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


public class CodeGenerator {
    final String WORKING_DIRECTORY = System.getProperty("user.dir") + "/pacman/levels";
    final String OUTPUT_FILENAME = WORKING_DIRECTORY + "/level1.js";

    public void createJavaFile() throws IOException {
        final File outputFile = new File(OUTPUT_FILENAME);
        try (
                /**
                 * The Try-with-resources pattern closes all resources in the ()-block.
                 * FileWriter automatically flushes on close:
                 * https://docs.oracle.com/javase/8/docs/api/java/io/Writer.html#close--
                 */
                final FileWriter fw = new FileWriter(outputFile);
        ) {
            final FormattingCodeWriter codeWriter = new FormattingCodeWriter(fw);
            codeWriter.append("// JavaScript file generated by CodeGenerator");
            codeWriter.blankLine();
            codeWriter.append(
                    "define([], function () {",
                    "return {",
                    "floor: 0,",
                    "point: 1,",
                    "fruit: 2,",
                    "wall: 3,",
                    "map:"
            );
            codeWriter.append(
                    PacmanParserExecutor.parseLevel().toString()
            );
            codeWriter.append(
                    "}\n",
                    "});"
            );
            codeWriter.write();
        }
    }

    public static void main(String args[]) throws IOException {
        System.out.println(System.getProperty("user.dir"));
        System.out.println("Starting code generation...");
        final CodeGenerator cg = new CodeGenerator();
        cg.createJavaFile();
        System.out.println("Finished code generation...");
    }
}

