import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


public class CodeGenerator {
    final String WORKING_DIRECTORY = System.getProperty("user.dir") + "/src/de/bht/se/battleship/";
    //final String MODEL_FILENAME = WORKING_DIRECTORY + "/codegen/battleship.txt";
    final String OUTPUT_FILENAME = WORKING_DIRECTORY + "/generatedSources/level1.js";
    PacmanParserExecutor codegen = new PacmanParserExecutor();

    public void createJavaFile() throws IOException {
        final File outputFile = new File(OUTPUT_FILENAME);
        try (
                //Introduce autoformatting CodeFormatter class
                //final FileReader fr = new FileReader(MODEL_FILENAME);
                //final Scanner modelScanner = new Scanner(fr);
                /**
                 * The Try-with-resources pattern closes all resources in the ()-block.
                 * FileWriter automatically flushes on close:
                 * https://docs.oracle.com/javase/8/docs/api/java/io/Writer.html#close--
                 */
                final FileWriter fw = new FileWriter(outputFile);
        ) {
            final FormattingCodeWriter codeWriter = new FormattingCodeWriter(fw);
            codeWriter.append("// Java file generated by CodeGenerator");
            codeWriter.blankLine();
            codeWriter.append(
                    "define([], function () {",
                        "return {",
                            "floor: 0,",
                            "point: 1,",
                            "fruit: 2,",
                            "wall: 3,",
                            "map:"
            );
           /* modelScanner.useDelimiter(",");
            for (int i = 0; modelScanner.hasNextLine() && i < 6; i++) {
                final String input = modelScanner.nextLine();
                codeWriter.append("{" + input + "},");
            }
            codeWriter.append(
                                "{" + modelScanner.nextLine() + "}",
                            "};",
                            "return gameboard;",
                        "}",
                    "}"
            );*/
            codeWriter.write();
        }
    }

    public static void main(String args[]) throws IOException {
        System.out.println(System.getProperty("user.dir"));
        System.out.println("Starting code generation...");
        final CodeGenerator cg = new CodeGenerator();
        cg.createJavaFile();
        System.out.println("Finished code generation...");
    }
}

