// Java file generated by MyCodeGenerator

package generatedSources;
public class AiMovesBuilder {
    public static String [] createAiMoves() {
        String [] AiMoves = {
        "A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7","A1","A2","G7"
        };
        return AiMoves;
    }
}
