// Java file generated by MyCodeGenerator

package generatedSources;
public class GameFieldBuilder {
    public static int[][] createGameField() {
        int[][] GameField = {
            {0,0,0,0,0,0,0},{0,0,0,1,1,1,1},{0,1,0,0,0,0,0},{0,1,0,0,0,0,0},{0,1,0,1,1,1,0},{0,1,0,0,0,0,0},{0,1,0,0,0,0,0}
        };
        return GameField;
    }
}
